error: cast from pointer to integer of different size [-Werror=pointer-to-int-cast]
On 32bit systems casts like (Dwarf_Unsigned)
applied to a pointer need to be
(Dwarf_Unsigned)(uintptr_t)
to avoid failing in compilations.
Four places.

Would not fail if one avoids --enable-wall and the like.
But now fixed.
	modified:   src/lib/libdwarf/dwarf_frame.c
	modified:   src/lib/libdwarf/dwarf_frame2.c